AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  # SNS Topics should be defined first since they're referenced by multiple functions
  TasksAssignmentNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: TasksAssignmentNotificationTopic

  TasksDeadlineNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: TasksDeadlineNotificationTopic

  ClosedTasksNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ClosedTasksNotificationTopic

  ReopenedTasksNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ReopenedTasksNotificationTopic

  # Cognito Resources
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: MyUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
        - Name: role
          AttributeDataType: String
          Mutable: true
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: MyUserPoolClient
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH

  # DynamoDB Table
  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TasksTable
      AttributeDefinitions:
        - AttributeName: TaskId
          AttributeType: S
      KeySchema:
        - AttributeName: TaskId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: MyApi
      StageName: prod
      Auth:
        DefaultAuthorizer: CognitoAuth
        Authorizers:
          CognitoAuth:
            UserPoolArn: !GetAtt CognitoUserPool.Arn

  # Lambda Functions
  TaskDeadlineNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: deadline_notification.lambda_handler
      Runtime: python3.11
      CodeUri: functions/tasks/
      Environment:
        Variables:
          TASKS_DEADLINE_TOPIC_ARN: !Ref TasksDeadlineNotificationTopic
          TABLE_NAME: !Ref TasksTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TasksTable
        - Statement:
            Effect: Allow
            Action:
              - sns:Publish
              - events:DeleteRule
              - events:RemoveTargets
            Resource: "*"

  AssignTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: assign_task.lambda_handler
      Runtime: python3.11
      CodeUri: functions/tasks/
      Environment:
        Variables:
          TASKS_ASSIGNMENT_TOPIC_ARN: !Ref TasksAssignmentNotificationTopic
          TASKS_DEADLINE_TOPIC_ARN: !Ref TasksDeadlineNotificationTopic
          TASKS_DEADLINE_FUNCTION_NAME: !Ref TaskDeadlineNotificationFunction
          TASKS_DEADLINE_FUNCTION_ARN: !GetAtt TaskDeadlineNotificationFunction.Arn

          TABLE_NAME: !Ref TasksTable
          AWS_ACCOUNT_ID: !Ref AWS::AccountId
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
        - Statement:
            Effect: Allow
            Action:
              - sns:Publish
              - events:PutRule
              - events:PutTargets
              - lambda:AddPermission
            Resource: 
              - !GetAtt TasksAssignmentNotificationTopic.TopicArn
              - !GetAtt TasksDeadlineNotificationTopic.TopicArn
              - !GetAtt TaskDeadlineNotificationFunction.Arn
              - "*"  # For EventBridge permissions
      Events:
        AssignTask:
          Type: Api
          Properties:
            Path: /tasks
            Method: post
            RestApiId: !Ref ApiGateway

  AddUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: add_user.lambda_handler
      Runtime: python3.11
      CodeUri: functions/users/
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !Ref CognitoUserPool
          TASKS_ASSIGNMENT_TOPIC_ARN: !Ref TasksAssignmentNotificationTopic
          TASKS_DEADLINE_TOPIC_ARN: !Ref TasksDeadlineNotificationTopic
          CLOSED_TASKS_TOPIC_ARN: !Ref ClosedTasksNotificationTopic
          REOPENED_TASKS_TOPIC_ARN: !Ref ReopenedTasksNotificationTopic
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action: 
              - cognito-idp:AdminCreateUser
              - cognito-idp:AdminAddUserToGroup
              - sns:Subscribe
              - sns:Publish
            Resource: 
              - !GetAtt CognitoUserPool.Arn
              - !GetAtt TasksAssignmentNotificationTopic.TopicArn
              - !GetAtt TasksDeadlineNotificationTopic.TopicArn
              - !GetAtt ClosedTasksNotificationTopic.TopicArn
              - !GetAtt ReopenedTasksNotificationTopic.TopicArn
      Events:
        AddUser:
          Type: Api
          Properties:
            Path: /users
            Method: post
            RestApiId: !Ref ApiGateway

  GetUserTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_user_tasks.lambda_handler
      Runtime: python3.11
      CodeUri: functions/tasks/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TasksTable
      Events:
        GetUserTasks:
          Type: Api
          Properties:
            Path: /tasks
            Method: get
            RestApiId: !Ref ApiGateway

  EditTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: edit_task.lambda_handler
      Runtime: python3.11
      CodeUri: functions/tasks/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
      Events:
        EditTask:
          Type: Api
          Properties:
            Path: /tasks
            Method: put
            RestApiId: !Ref ApiGateway

  DeleteTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: delete_task.lambda_handler
      Runtime: python3.11
      CodeUri: functions/tasks/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
      Events:
        DeleteTask:
          Type: Api
          Properties:
            Path: /tasks
            Method: delete
            RestApiId: !Ref ApiGateway

  GetAllTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_all_tasks.lambda_handler
      Runtime: python3.11
      CodeUri: functions/tasks/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TasksTable
      Events:
        GetAllTasks:
          Type: Api
          Properties:
            Path: /tasks/all
            Method: get
            RestApiId: !Ref ApiGateway

  GetAllUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_all_users.lambda_handler
      Runtime: python3.11
      CodeUri: functions/users/
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !Ref CognitoUserPool
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:ListUsers
              Resource: !GetAtt CognitoUserPool.Arn
      Events:
        GetAllUsers:
          Type: Api
          Properties:
            Path: /users
            Method: get
            RestApiId: !Ref ApiGateway
            
  TestApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: testapi.lambda_handler
      Runtime: python3.11
      CodeUri: functions/tasks/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TasksTable
      Events:
        GetAllTasks:
          Type: Api
          Properties:
            Path: /tasks/test
            Method: get
            RestApiId: !Ref ApiGateway

